Add new name
BUGS-NYU/bugs-nyu.github.io pull request #109
Opened 2023-10-20 21:29 UTC by SnazzyBeatle115

2023-10-21 16:14 UTC, unknown requested changes
Hey, it looks you created `ds6870.md` in the root directory. Please move that file to `src/data/members/`, then commit your change and push again.

2023-10-22 01:25 UTC, SnazzyBeatle115 commented
ok i did

2023-10-22 01:26 UTC, calvinatian approved these changes

2023-10-22 01:28 UTC, unknown approved these changes
Looks good, thanks!

2023-10-22 01:28 UTC, merged