alumni page
BUGS-NYU/bugs-nyu.github.io pull request #73
Opened 2023-03-14 04:37 UTC by aminoa

collected alumni data, made alumni listing page.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Veena was BUGS's predident from 2018 to 2020. Alumni who studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry
```suggestion
      `Veena was BUGS's predident from 2018 to 2020. Alumni who studied Computer Science at CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and plays card games.`,
```
Maybe get rid of their current occupation since it probably will be outdated.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
Not sure if this data is available but it would be nice to see the years previous members were part of the club (e.g. 2018-2020) and/or their graduation year.

Also should we order the data somehow? Maybe by graduation year or alphabetically. Or is the data already in some order?

Most of the suggested changes are for consistency. Like for strings single quotes, double quotes, and template literals were used. In the suggested changes I modified all the descriptions to use template literals.

2023-03-14 06:13 UTC, calvinatian commented on src/pages/alumni.tsx
> +              <b>{alum.name}</b>: {alum.description}
```suggestion
              <b>{alum.name}</b>:
              <div className='mx-4'>{alum.description}</div>
```
I think adding some spacing between the name and description would be good.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    Aaditya was the former treasurer.`,
```suggestion
    description: `Aaditya is an alumni majoring in Economics and Mathematics, Aaditya spends way too much time in Stern (#IAmStern). In his free time he likes to listen to music, take long walks, and read Econ papers, sometimes simultaneously. Aaditya was a former treasurer.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    In my free time, I work with a variety of organizations to help find dogs and cats' homes. I also love painting and digital art so when I'm not working with animals, I am creating. Sonia was the
```suggestion
    description: `I'm Sonia and I'm an alumni at New York University double majoring in Computer Science and Media, Culture, and Communications. I am interested in game design, art, and I love animals. In my free time, I work with a variety of organizations to help find dogs and cats' homes. I also love painting and digital art so when I'm not working with animals, I am creating. Sonia was a former director of marketing & communications.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    Khanh was the former president.`,
```suggestion
    description: `Khanh is an alumni from Vietnam majoring in Computer Science. BROCKHAMPTON is his all-time favorite boyband. Outside of school, he enjoys trying out good food, exploring the city and contributing to projects. Khanh was a former president.`,
```
Keep consistency and have all data on one line. The rendering does not seem to preserve the newlines anyway.

Also remove reference to their university year since it is no longer relevant or accurate.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    Besides, he likes listening to music, reading about history, and travelling. He was the former secretary.`,
```suggestion
    description: `Bruce is a junior from China studying Computer Science and Mathematics. Outside of class, he is crazy in soccer (especially in Chelsea) and basketball. He spends tons of time playing FIFA (most of the time playing Chelsea). Besides, he likes listening to music, reading about history, and traveling. Bruce was a former secretary.`,
```
Fix typo and refer by name

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'Evan is a Junior studying CS at CAS. In his free time he enjoys working on too many side projects, expanding his record collection, and making memes for @nyumsfbt. He was a former full stack d
```suggestion
      `Evan is an alumni majoring in CS at CAS. In his free time he enjoys working on too many side projects, expanding his record collection, and making memes for @nyumsfbt. Evan was a former full stack developer.`,
```
Use template literals (``) for all descriptions for consistency.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    He is a big foodie and enjoys trying foods from different cultures. He was a former event coordinator.`,
```suggestion
    description: `Samuel is an alumni at CAS majoring in Computer Science and minoring in Web Design and Game Design. He was born and raised in Taiwan, but studied in Singapore for high school before coming to New York. He is a big foodie and enjoys trying foods from different cultures. He was a former event coordinator.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'I am a Graduate Student in Information Systems at GSAS. I hail from Hyderabad(India) and love travelling and exploring new places. Usually spotted listening to music and engaging in debates wi
```suggestion
      `I am a Graduate Student in Information Systems at GSAS. I hail from Hyderabad(India) and love traveling and exploring new places. Usually spotted listening to music and engaging in debates with friends. Vishal was a former event coordinator.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'Nadira was one of the Founders of BUGS. An alumni studied Computer Science in CAS. Originally from Tanzania, Nadira loves travelling, scuba diving and wildlife. She’s excited about open source
```suggestion
      `Nadira was one of the Founders of BUGS. Alumni who studied Computer Science at CAS. Originally from Tanzania, Nadira loves travelling, scuba diving and wildlife. She’s excited about open source principles and making impactful contributions.`,
```
> Alumni who studied Computer Science at CAS.

I don't think this is proper grammar but changed it to keep consistency with the other descriptions.

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'David was one of the Founders of BUGS. Alumni from California who studied Biology with three minors, and loves both carbon based life and silicon based life to equal extents.',
```suggestion
      `David was one of the Founders of BUGS. Alumni from California who studied Biology with three minors, and loves both carbon based life and silicon based life to equal extents.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'Yuchen is a CS and Data Science major at CAS. He likes to eat ramen, watch movies, meet new people, and work on fun projects. He was a former full stack developer.',
```suggestion
      `Yuchen is a CS and Data Science major at CAS. He likes to eat ramen, watch movies, meet new people, and work on fun projects. He was a former full stack developer.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    tangible code based projects!`,
```suggestion
    description: `Ananditha was one of the Founders of BUGS. Alunmi who studied Math and CS at Courant. Having started to code only after she arrived at NYU, she is excited to mentor new members that may not know how to make their ideas translate into tangible code based projects!`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    In her free time, she loves to explore the different boroughs in the city and try food from different cultures.`,
```suggestion
    description: `Shelly Cao was BUGS's Director of Outreach in 2019. Alumni who majored in Computer Science with minors in Math and Business Study. She comes from a small city in China called Jingzhou and even her Chinese friends are clueless as to where it is. In her free time, she loves to explore the different boroughs in the city and try food from different cultures.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'Alumni from Connecticut who majored in Computer Science and minored in Business Studies and Math. You may also find her on campus doing work for CAS Student Council.',
```suggestion
      `Alumni from Connecticut who majored in Computer Science and minored in Business Studies and Math. You may have also found her on campus doing work for CAS Student Council.`,
```
Update to past tense

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Eric was BUGS's Secretary. Alumni from Stern who majored in Business and Mathematics and minored in Computer Science. He likes to play basketball, listens to music and read about philosophy.",
```suggestion
      `Eric was BUGS's Secretary. Alumni from Stern who majored in Business and Mathematics and minored in Computer Science. He likes to play basketball, listens to music and read about philosophy.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Edmond was BUGS's Director of Communications. Alumni from CAS who majored in Computer Science and minored in Business Studies. He likes cars, being a foodie and traveling.",
```suggestion
      `Edmond was BUGS's Director of Communications. Alumni from CAS who majored in Computer Science and minored in Business Studies. He likes cars, being a foodie and traveling.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Joanna was BUGS's Director of Marketing. Alumni from CAS who majored in Mathematics and Computer Science. She enjoys working on machine learning research, supporting local restaurants, capturi
```suggestion
      `Joanna was BUGS's Director of Marketing. Alumni from CAS who majored in Mathematics and Computer Science. She enjoys working on machine learning research, supporting local restaurants, capturing NYC through her lens, and taking a walk at sunset.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    In his free time he enjoys going on long walks and taking longer naps.`,
```suggestion
    description: `Albert was BUGS's Vice President. Alumni from CAS who majored in Computer Science. He has worked on Schedge, an API for NYU course data, as well as HumanToHuman, an application to help researchers study human interaction patterns. In his free time he enjoys going on long walks and taking longer naps.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    simple CNN for puzzle solving, home automation programs, and building mobile/web apps. He's a SWE at NextJump.`,
```suggestion
    description: `Brian was BUGS's webmaster from 2018 to 2020. Alumni from CAS who majored in Computer Science and minored in Cyber Security, Web Development, & Studio Art. Outside of class you can find him working a variety of things including custom IoT devices, simple CNN for puzzle solving, home automation programs, and building mobile/web apps.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Ami was BUGS's Event Coordinator from 2018 to 2020. Alumni from California who studied Computer Science and minored in Web Design. In her free time, she loves spending time with family, runnin
```suggestion
      `Ami was BUGS's Event Coordinator from 2018 to 2020. Alumni from California who studied Computer Science and minored in Web Design. In her free time, she loves spending time with family, running, and of course, coding!`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Alumni from Woodmere, New York who studied Computer Science. Outside of BUGS, you can find him coaching hockey at a local high school. He's a Backend Programmer at SomethingDigital.",
```suggestion
      `Alumni from Woodmere, New York who studied Computer Science. Outside of BUGS, you can find him coaching hockey at a local high school.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +    Candice is traveling or planning for her 23rd country to visit.`,
```suggestion
    description: `Candice Shen was BUGS's Director of Communications in 2019. Alumni from Steinhardt who majored in Media, Culture, and Communication and minored in Web Design. If you cannot find her outside of class, Candice is traveling or planning for her 23rd country to visit.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      "Deanna was BUGS's Director of Communication in 2019. Alumni from CAS who studied Computer Science with minors in Web Design and Linguistics. Outside of school, Deanna can be found at a local r
```suggestion
      `Deanna was BUGS's Director of Communication in 2019. Alumni from CAS who studied Computer Science with minors in Web Design and Linguistics. Outside of school, Deanna can be found at a local restaurant or art museum.`,
```

2023-03-14 06:13 UTC, calvinatian commented on src/data/alumni.ts
> +      'Alumni from Singapore who majored in Computer Science and Business. He likes reading, writing, coding, and gaming.',
```suggestion
      `Alumni from Singapore who majored in Computer Science and Business. He likes reading, writing, coding, and gaming.`,
```

2023-03-14 15:03 UTC, aminoa commented on src/data/alumni.ts
Ordering by graduation year makes the most sense for this page; I combined two data lists from the previous BUGS website which had the current members and an alumni section. I wasn't sure how the alumni section was ordered so I left that order intact here. If we later get all the years active for members, we could reorder it accordingly.

The consistency changes to use only template literals is good. I may rewrite the descriptions to all be in 3rd person so the descriptions are less jarring.

2023-03-14 17:51 UTC, aminoa commented
Added grad year for most students, reformatted text to be in 3rd person, sorted descending by grad year

2023-03-14 22:45 UTC, nedjulius approved these changes

2023-03-15 07:15 UTC, calvinatian commented
The latest commit still has a mix of single and double quotes.

When referring to the alum's previous position some refer to them by name and others by pronoun. I think it would be good to make them consistent.

> Khanh was the former president.

vs.

> He was the former secretary.

2023-03-15 16:38 UTC, aminoa commented
I replaced all the pronouns with the names for consistency; when I commit my changes, some of the quotation marks were automatically are converted to apostrophes so I left those as they are.

2023-03-17 15:48 UTC, unknown requested changes

2023-03-17 15:48 UTC, unknown commented on package-lock.json
Is there a way to restore the package-lock file?

2023-03-17 15:48 UTC, unknown commented on src/pages/alumni.tsx
> +              <div className='mx-4'>{alum.description}</div>
I think it's bad practice for a `div` element to be a child of a `p` element. A quick fix could be to just replace the outer `p` tag with a `div` tag.

2023-03-17 15:48 UTC, unknown commented on src/pages/alumni.tsx
> +              <b>{alum.name}</b> ({alum.graduation}):
While there's nothing wrong with using `b` tags, I think it'd be better to style font weights with the Tailwind class "font-bold" i.e. replacing `<b>...</b>` with `<span className='font-bold'>...</span>`. If you're changing the outer `p` tag with `div`, maybe wrap this line in a `p` tag.

2023-03-17 15:48 UTC, unknown commented on src/data/alumni.ts
Should the descriptions be made to also use consistent verb tenses?

2023-03-18 00:15 UTC, aminoa commented on src/data/alumni.ts
It is usually context dependent. For activities and hobbies, I usually kept those present tense. For stuff related to education, I had those descriptions in the past tense.

2023-03-18 00:28 UTC, aminoa commented
I made the requested changes (except for changing the tenses for the descriptions)

2023-03-18 05:17 UTC, nedjulius commented
You don't have to manually change the quotation marks. We have `prettier` pre-commit hook that formats your code according to our set guidelines. The reason why you get a mix of single and double marks is because some sentences have words with apostrophes, and they must be enclosed in double quotation marks.

2023-03-18 22:12 UTC, unknown approved these changes

2023-03-21 04:02 UTC, calvinatian commented on package-lock.json
Probably better to keep the newline. I think its used in diffs

2023-03-21 04:02 UTC, calvinatian commented on src/data/alumni.ts
> +      "Veena was BUGS' predident from 2018 to 2020 and studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and pla
```suggestion
      "Veena was BUGS's predident from 2018 to 2020 and studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and plays card games.",
```

2023-03-21 04:02 UTC, calvinatian commented on src/data/alumni.ts
> +      'Nadira was one of the Founders of BUGS and studied Computer Science in CAS. Originally from Tanzania, Nadira loves travelling, scuba diving and wildlife. She’s excited about open source princi
```suggestion
      "Nadira was one of the Founders of BUGS and studied Computer Science in CAS. Originally from Tanzania, Nadira loves travelling, scuba diving and wildlife. She's excited about open source principles and making impactful contributions.",
```
Not sure if this is from the formatter but I think using a regular apostrophe is better than the unicode for quotation mark (U+2019). Or if we want to stick with the unicode we should change all the other apostrophes to the unicode mark.

2023-03-21 17:07 UTC, aminoa commented on src/data/alumni.ts
> +      "Veena was BUGS' predident from 2018 to 2020 and studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and pla
That isn't correct grammar so I'll leave it as it is

2023-03-21 17:08 UTC, merged

2023-03-22 03:18 UTC, calvinatian commented on src/data/alumni.ts
> +      "Veena was BUGS' predident from 2018 to 2020 and studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and pla
But for all the other descriptions you use `BUGS's`

2023-03-22 05:12 UTC, aminoa commented on src/data/alumni.ts
> +      "Veena was BUGS' predident from 2018 to 2020 and studied Computer Science in CAS. She loves to talk about code with other people. In her free time, Veena goes to the gym, makes jewelry, and pla
Yeah, those are mistakes then. I'll fix them.